name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.0.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.0.0
      - run: npm ci
      - run: npm run ci
